import type { BoardState, Card } from "./types";
const now = new Date();
const ago = (hours: number) =>
  new Date(now.getTime() - hours * 3600000).toISOString();
const task = (
  id: string,
  title: string,
  column: string,
  labels: string[],
  author: string,
  position: number,
  description = "",
  read = false,
): Card => ({
  id,
  workspace_id: "salescrew",
  title,
  column_id: column,
  project_id: column === "work" || column === "done" ? "nespresso" : column,
  label_ids: labels,
  created_by: author,
  assignee_id: author,
  position,
  description,
  reviewed_at: read ? ago(4) : null,
  reviewed_by: read ? "kilian" : null,
  completed_at: column === "done" ? ago(2) : null,
  created_at: ago(48),
  updated_at: ago(2),
});
export const createSeed = (): BoardState => ({
  workspace_blocks: [],
  workspaces: [{ id: "salescrew", name: "SalesCrew", color: "green" }],
  profiles: [
    {
      id: "kilian",
      name: "Kilian",
      email: "kilian@example.com",
      role: "admin",
      default_column_id: "spark",
      default_workspace_id: "salescrew",
      color: "green",
      active: true,
    },
    {
      id: "philip",
      name: "Philip",
      email: "philip@example.com",
      role: "admin",
      default_column_id: "rover",
      default_workspace_id: "salescrew",
      color: "blue",
      active: true,
    },
    {
      id: "anna",
      name: "Anna Leitner",
      email: "anna@example.com",
      role: "mitarbeiter",
      default_column_id: "spark",
      default_workspace_id: "salescrew",
      color: "orange",
      active: true,
    },
    {
      id: "ben",
      name: "Ben Wagner",
      email: "ben@example.com",
      role: "mitarbeiter",
      default_column_id: "nespresso",
      default_workspace_id: "salescrew",
      color: "purple",
      active: true,
    },
    {
      id: "david",
      name: "David Lang",
      email: "david@example.com",
      role: "mitarbeiter",
      default_column_id: "rover",
      default_workspace_id: "salescrew",
      color: "rose",
      active: true,
    },
  ],
  columns: [
    {
      id: "spark",
      name: "SPARK",
      color: "orange",
      kind: "project",
      workspace_id: "salescrew",
      position: 0,
    },
    {
      id: "rover",
      name: "ROVER",
      color: "purple",
      kind: "project",
      workspace_id: "salescrew",
      position: 1,
    },
    {
      id: "obi",
      workspace_id: "salescrew",
      name: "OBI",
      color: "rose",
      kind: "project",
      position: 2,
    },
    {
      id: "nespresso",
      name: "Nespresso",
      color: "blue",
      kind: "project",
      workspace_id: "salescrew",
      position: 3,
    },
    {
      id: "work",
      name: "In Arbeit",
      color: "orange",
      kind: "work",
      workspace_id: "salescrew",
      position: 4,
    },
    {
      id: "done",
      workspace_id: "salescrew",
      name: "Fertig",
      color: "green",
      kind: "done",
      position: 5,
    },
  ],
  labels: [
    {
      id: "feature",
      name: "Feature",
      color: "green",
      workspace_id: "salescrew",
    },
    {
      id: "improve",
      name: "Verbesserung",
      color: "blue",
      workspace_id: "salescrew",
    },
    { id: "bug", name: "Bug", color: "rose", workspace_id: "salescrew" },
    {
      id: "feedback",
      name: "Feedback",
      color: "purple",
      workspace_id: "salescrew",
    },
    {
      id: "priority",
      name: "Priorität",
      color: "orange",
      workspace_id: "salescrew",
    },
  ],
  cards: [
    task(
      "c1",
      "Dashboard – Mitbewerb",
      "spark",
      ["feature", "priority"],
      "anna",
      1024,
      "Die Mitbewerber-Platzierungen sollen im Dashboard übersichtlich gegenübergestellt werden.\n\nBitte die Auswertung nach Region und Zeitraum filterbar machen. Die aktuelle Ansicht dient als Ausgangspunkt.",
      true,
    ),
    task(
      "c2",
      "Passwort-vergessen-Route",
      "spark",
      ["bug"],
      "kilian",
      2048,
      "Den Link zum Zurücksetzen des Passworts auf der Login-Seite ergänzen.",
    ),
    task(
      "c3",
      "Neue Filter für die Auswertung",
      "spark",
      ["improve"],
      "anna",
      3072,
      "Region, Zeitraum und Marke als kombinierbare Filter anbieten.",
    ),
    task(
      "c4",
      "Feedback zur mobilen Ansicht",
      "spark",
      ["feedback"],
      "philip",
      4096,
      "Abstände und Lesbarkeit der Tabellen auf kleinen Displays prüfen.",
      true,
    ),
    task(
      "c5",
      "Perfect Store Auswertung verfeinern",
      "rover",
      ["improve"],
      "philip",
      1024,
      "Die Auswertung soll Abweichungen zum Vormonat direkt sichtbar machen.",
      true,
    ),
    task(
      "c6",
      "Zugang zu Rover für Mars",
      "rover",
      ["feature"],
      "david",
      2048,
      "Einen neuen Zugang für das Mars-Team vorbereiten.",
    ),
    task(
      "c7",
      "Distributionsprozente in der GL-Historie",
      "rover",
      ["feature", "feedback"],
      "david",
      3072,
      "Die Distributionsprozente im Verlauf der Geschäftsleitung anzeigen.",
    ),
    task(
      "c8",
      "Ansicht der KPIs",
      "nespresso",
      ["improve", "priority"],
      "ben",
      1024,
      "Die wichtigsten KPIs in einer kompakten Übersicht zusammenfassen.",
      true,
    ),
    task(
      "c9",
      "Registrierte Mitarbeiter löschen",
      "nespresso",
      ["improve"],
      "ben",
      2048,
    ),
    task(
      "c10",
      "Einsatzplan überarbeiten",
      "nespresso",
      ["feature"],
      "kilian",
      3072,
      "Die bestehende Ansicht vereinfachen und klarer strukturieren.",
    ),
    task(
      "c11",
      "OBI Automation",
      "work",
      ["feature"],
      "philip",
      1024,
      "Den wöchentlichen Export automatisieren.",
      true,
    ),
    task(
      "c12",
      "Dokumentation aktualisieren",
      "done",
      ["improve"],
      "ben",
      1024,
      "Alle neuen Abläufe sind dokumentiert.",
      true,
    ),
    task(
      "c13",
      "Shelf-Meldungen korrigieren",
      "done",
      ["bug"],
      "philip",
      2048,
      "",
      true,
    ),
  ],
  comments: [
    {
      id: "comment1",
      card_id: "c1",
      author_id: "anna",
      body: "Die aktuelle Auswertung ist bereit. Könnt ihr einen Blick darauf werfen?",
      created_at: ago(24),
    },
    {
      id: "comment2",
      card_id: "c1",
      author_id: "philip",
      body: "Sieht schon gut aus! Den Vergleich zum Vormonat würde ich noch ergänzen.",
      created_at: ago(0.3),
    },
    {
      id: "comment3",
      card_id: "c5",
      author_id: "david",
      body: "Die neue Ansicht ist bereit für dein Feedback.",
      created_at: ago(1),
    },
    {
      id: "comment4",
      card_id: "c8",
      author_id: "ben",
      body: "Die KPI-Ansicht ist aktualisiert. Passt das für euch?",
      created_at: ago(2),
    },
  ],
  attachments: [],
  notifications: [
    {
      id: "n1",
      recipient_id: "kilian",
      actor_id: "philip",
      workspace_id: "salescrew",
      card_id: "c1",
      comment_id: "comment2",
      event_type: "comment.created",
      subject: "Dashboard – Mitbewerb",
      event_key: "comment:comment2",
      body: "Sieht schon gut aus! Den Vergleich zum Vormonat würde ich noch ergänzen.",
      created_at: ago(0.3),
      seen_at: null,
    },
    {
      id: "n2",
      recipient_id: "kilian",
      actor_id: "david",
      workspace_id: "salescrew",
      card_id: "c5",
      comment_id: "comment3",
      event_type: "comment.created",
      subject: "Einsatzplan überarbeiten",
      event_key: "comment:comment3",
      body: "Die neue Ansicht ist bereit für dein Feedback.",
      created_at: ago(1),
      seen_at: null,
    },
    {
      id: "n3",
      recipient_id: "kilian",
      actor_id: "ben",
      workspace_id: "salescrew",
      card_id: "c8",
      comment_id: "comment4",
      event_type: "comment.created",
      subject: "Auswertung aktualisieren",
      event_key: "comment:comment4",
      body: "Die KPI-Ansicht ist aktualisiert. Passt das für euch?",
      created_at: ago(2),
      seen_at: null,
    },
  ],
});
